#this part should be executed after pcr.rb gathered all clients pcrs


agents = search(:node, "recipes:oat\\:\\:client") || []
agents.each do |agent|
  #add all the agents into oat
  oem_name="#{agent[:name]}-oem"
  oem_description="#{agent[:name]} #{agent[:dmi][:bios][:base_board][:product_name]} #{agent[:dmi][:bios][:base_board][:serial_number]} generated by crowbar"
  ##############reg oem here############
  os_name="#{agent[:name]}-os"
  os_version="#{agent[:lsb][:release]}"
  os_description="#{agent[:name]} #{agent[:lsb][:description]}"
  ##############reg os here############
  mle_oem_name="#{agent[:name]}-mle-oem"
  mle_oem_version="1" #we dont want to up version automaticaly or provide any interface to do it, it should be done manualy
  mle_oem_attestation_type="PCR"
  mle_oem_type="BIOS"
  mle_oem_description="#{agent[:name]} BIOS mle generated by crowbar"
  ##############reg oem mle here############
  mle_vmm_name="#{agent[:name]}-vmm-oem"
  mle_vmm_version="1"
  mle_vmm_attestation_type="PCR"
  mle_vmm_type="VMM"
  mle_vmm_description="#{agent[:name]} #{agent[:kernel][:release] #{agent[:kernel][:version] VMM mle generated by crowbar}"
  ##############reg vmm here############
  host_name="#{agent[:name]}"
  host_ip="#{agent[:crowbar][:network][:admin][:address]}"
  host_port="12345" #seems deprecated, used only with active polling
  host_description="#{agent[:name]} host generated by crowbar"
  ##############reg host here############
  (0..7).each do |n|
    pcr_name=n
    pcr_val=agent[:oat][:pcr][pcr_name]
    #####whitelist pcr with mle_oem_name mle_oem_version oem_name#####
  end
  (17..19).each do |n|
    pcr_name=n
    pcr_val=agent[:oat][:pcr][pcr_name]
    #####whitelist pcr with mle_vmm_name mle_vmm_version os_name os_version#####
  end
end
